version: '3'
services:
    sample-generator:
        image: openapitools/openapi-generator-cli
        command: generate -i /local/openapi.yml -g go-gin-server -o /project
        volumes:
            - ./openapi:/local
            - .:/project

